# Generated by Django 5.2.13 on 2026-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_net_payable_remove_sale_quantity_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='manual_first_process',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='manual_purity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='qty_tolas',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='tola_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
