# Generated by Django 5.2.13 on 2026-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DensityPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('purity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Density Purity Mapping',
                'verbose_name_plural': 'Density Purity Mappings',
                'ordering': ['density'],
            },
        ),
    ]
