# Generated by Django 5.2.13 on 2026-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('density_purity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='densitypurity',
            options={},
        ),
        migrations.AlterField(
            model_name='densitypurity',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True),
        ),
        migrations.AlterField(
            model_name='densitypurity',
            name='purity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
